# runs tests for push-events, for pull requests and using cron schedule:
name: Run Robot Framework Tests
on:
  push:
    # runs tests for commits pushed to master
    branches:
      - master
    # do not run tests if file README.md changes
    paths-ignore:
      - '**.md'
    # run tests for GitHub Pull requests. Test result is visible in the Pull Request page.

  pull_request:
    paths-ignore:
      - '**.md'
    inputs:
      DINOSAUR:
        description: 'Creature that is expected to be dinosaur:'
        default: achillobator
        # Input has to be provided for the workflow to run
        required: true
      NOT_DINOSAUR:
        description: 'Creature that is not a dinosaur:'
        # Default value if no value is explicitly provided
        default: dog
        # Input has to be provided for the workflow to run
        required: true
      tag:
        description: 'Tag for tests to run. Use "*" to run all'
        # Default value if no value is explicitly provided
        default: dinosaur
        # Input has to be provided for the workflow to run
        required: true
  schedule:
    # run tests once a year in January 1st
    - cron:  '0 0 1 1 *'
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      DINOSAUR:
        description: 'Creature that is expected to be dinosaur:'
        default: achillobator
        # Input has to be provided for the workflow to run
        required: true
      NOT_DINOSAUR:
        description: 'Creature that is not a dinosaur:'
        # Default value if no value is explicitly provided
        default: dog
        # Input has to be provided for the workflow to run
        required: true
      tag:
        description: 'Tag for tests to run. Use "*" to run all'
        # Default value if no value is explicitly provided
        default: dinosaur
        # Input has to be provided for the workflow to run
        required: true
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create folder for reports
        run: mkdir reports
      - name: Run Robot Framework Tests
        run: |
          docker run \
            -v ${PWD}/reports:/opt/robotframework/reports:Z \
            -v ${PWD}/tests:/opt/robotframework/tests:Z \
            -e ROBOT_OPTIONS="--variable DINOSAUR:${{ github.event.inputs.DINOSAUR }} --variable NOT_DINOSAUR:${{ github.event.inputs.NOT_DINOSAUR }} --include ${{ github.event.inputs.tag }}" \
            --user $(id -u):$(id -g) \
            ppodgorsek/robot-framework:latest
      - name: Upload reports
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          # set path to Robot Framework results reports. Exclude dummy file that is needed because of ppodgorsek image priviledges.
          path: ${{ github.workspace }}/reports
  generate_report:
    if: always()
    needs: [ run_tests ]
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v2
      - name: Download reports
        uses: actions/download-artifact@v1
        with:
          name: reports
      - name: Send report to commit
        uses: joonvena/robotframework-reporter-action@v2.1
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}